"""Add image_urls column to tasks table

Revision ID: 20464827d967
Revises: 4c0c08a8a06d
Create Date: 2026-04-03 12:19:05.495399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20464827d967'
down_revision: Union[str, Sequence[str], None] = '4c0c08a8a06d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('image_urls', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'image_urls')
    # ### end Alembic commands ###
