"""Add last_seen column to users table

Revision ID: 4c0c08a8a06d
Revises: 4a3f4ce2fb9c
Create Date: 2026-04-02 19:23:28.183460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c0c08a8a06d'
down_revision: Union[str, Sequence[str], None] = '4a3f4ce2fb9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
