"""update_models_cloudinary_fallback

Revision ID: e8b933b36638
Revises: 
Create Date: 2026-03-07 06:43:41.807967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e8b933b36638'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_comments', sa.Column('attachment_url', sa.String(length=500), nullable=True))
    op.add_column('task_comments', sa.Column('attachment_filename', sa.String(length=255), nullable=True))
    op.add_column('task_comments', sa.Column('is_edited', sa.Boolean(), nullable=True))
    op.add_column('task_comments', sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('task_comments', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task_comments', 'task_comments', ['parent_id'], ['id'])
    op.add_column('tasks', sa.Column('requirements', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('requirements_checklist', sa.JSON(), nullable=True))
    op.add_column('tasks', sa.Column('requirements_completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('client_name', sa.String(length=255), nullable=True))
    op.add_column('tasks', sa.Column('company_name', sa.String(length=255), nullable=True))
    op.add_column('tasks', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.add_column('tasks', sa.Column('image_filename', sa.String(length=255), nullable=True))
    op.alter_column('tasks', 'category',
               existing_type=postgresql.ENUM('DEVELOPMENT', 'MARKETING', 'SALES', 'HR', 'FINANCE', 'OPERATIONS', 'OTHER', name='taskcategory'),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.add_column('users', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('avatar_filename', sa.String(length=255), nullable=True))
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('OWNER', 'ADMIN', 'EMPLOYEE', name='userrole'),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.String(length=100),
               type_=postgresql.ENUM('OWNER', 'ADMIN', 'EMPLOYEE', name='userrole'),
               existing_nullable=False)
    op.drop_column('users', 'avatar_filename')
    op.drop_column('users', 'avatar_url')
    op.alter_column('tasks', 'category',
               existing_type=sa.String(length=100),
               type_=postgresql.ENUM('DEVELOPMENT', 'MARKETING', 'SALES', 'HR', 'FINANCE', 'OPERATIONS', 'OTHER', name='taskcategory'),
               existing_nullable=False)
    op.drop_column('tasks', 'image_filename')
    op.drop_column('tasks', 'image_url')
    op.drop_column('tasks', 'company_name')
    op.drop_column('tasks', 'client_name')
    op.drop_column('tasks', 'requirements_completed_at')
    op.drop_column('tasks', 'requirements_checklist')
    op.drop_column('tasks', 'requirements')
    op.drop_constraint(None, 'task_comments', type_='foreignkey')
    op.drop_column('task_comments', 'parent_id')
    op.drop_column('task_comments', 'edited_at')
    op.drop_column('task_comments', 'is_edited')
    op.drop_column('task_comments', 'attachment_filename')
    op.drop_column('task_comments', 'attachment_url')
    # ### end Alembic commands ###
